apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    app: calculator
spec:
  selector:
    app: calculator
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
