- name: docker build and push
  hosts: localhost

  tasks:
    - name: Delete build directory
      command: rm -rf build
    - name: Create build directory
      command: mkdir build
    - name: Build Docker Image
      command: docker build -t calculator .
      args:
        chdir: /Users/yash/.jenkins/workspace/Calculator

    - name: tag image
      command: docker tag calculator yashrtalele/calculator_cpp:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: yashrtalele
        password: Y97^5Samaiyra*

    - name: Push image
      command: docker push yashrtalele/calculator_cpp:latest

